spring.datasource.url=jdbc:h2:mem:gameapi

spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=roor
spring.datasource.password=Bd@12082306!**

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



server.port=${PORT:8080}